const express = require("express")
const cookieParser = require("cookie-parser")
const cors = require("cors")
const puppeteer = require("puppeteer")

const app = express()

app.use(express.json())
app.use(cookieParser())

// CORS configuration for both development and production
const allowedOrigins = [
    "http://localhost:5173",           // Local development
    process.env.FRONTEND_URL,          // Render or other deployment URL
    "https://gen-ai-resume-analyzer.onrender.com" // Default Render domain (replace with your actual domain)
].filter(origin => origin) // Remove undefined entries

app.use(cors({
    origin: allowedOrigins,
    credentials: true
}))

// /require all the routes here
const authRouter = require("./routes/auth.routes")
const interviewRouter = require("./routes/interview.routes")

// using all the routes here
app.use("/api/auth", authRouter)
app.use("/api/interview", interviewRouter)

// Test route for Puppeteer
app.get("/api/test-pdf", async (req, res) => {
    try {
        const puppeteer = require("puppeteer")
        console.log("Testing Puppeteer PDF generation...")
        const browser = await puppeteer.launch({
            headless: true,
            args: ["--no-sandbox", "--disable-setuid-sandbox"]
        })
        const page = await browser.newPage()
        await page.setContent("<h1>Test PDF</h1><p>This is a test PDF generated by Puppeteer.</p>")
        const pdfBuffer = await page.pdf({ format: "A4" })
        await browser.close()

        console.log(`Test PDF generated, size: ${pdfBuffer.length} bytes`)
        console.log("PDF header:", pdfBuffer.toString('ascii', 0, 10))

        res.set({
            "Content-Type": "application/pdf",
            "Content-Disposition": "attachment; filename=test.pdf"
        })
        res.send(pdfBuffer)
    } catch (error) {
        console.error("Puppeteer test failed:", error.message)
        res.status(500).json({ error: error.message })
    }
})

// Test route for simple PDF
app.get("/api/test-simple-pdf", async (req, res) => {
    try {
        const puppeteer = require("puppeteer")
        console.log("Testing simple PDF generation...")

        const browser = await puppeteer.launch({
            headless: true,
            args: ["--no-sandbox", "--disable-setuid-sandbox"]
        })

        const page = await browser.newPage()
        await page.setContent(`
            <!DOCTYPE html>
            <html>
            <head><title>Simple Test</title></head>
            <body><h1>Hello World</h1><p>This is a simple test PDF.</p></body>
            </html>
        `, { waitUntil: "networkidle0" })

        // Wait for content to load (alternative to waitForTimeout)
        await new Promise(resolve => setTimeout(resolve, 1000))

        const pdfBuffer = await page.pdf({ format: "A4" })
        await browser.close()

        console.log(`Simple PDF generated, size: ${pdfBuffer.length} bytes`)
        console.log("PDF header:", pdfBuffer.toString('ascii', 0, 5))

        if (pdfBuffer.length === 0) {
            throw new Error("Generated PDF is empty")
        }

        // Skip validation for now to test basic functionality
        // if (!pdfBuffer.toString('ascii', 0, 5).startsWith('%PDF-')) {
        //     console.error("Invalid PDF generated")
        //     console.error("First 100 bytes:", pdfBuffer.toString('ascii', 0, 100))
        //     throw new Error("Generated PDF is not valid")
        // }

        res.set({
            "Content-Type": "application/pdf",
            "Content-Disposition": "attachment; filename=simple-test.pdf",
            "Content-Length": pdfBuffer.length
        })
        res.send(pdfBuffer)
    } catch (error) {
        console.error("Simple PDF test failed:", error.message)
        res.status(500).json({ error: error.message, stack: error.stack })
    }
})

// Test route for resume PDF generation
app.get('/api/test-resume-pdf', async (req, res) => {
    try {
        const testResumeHtml = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>Test Resume</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 20px; }
                    h1 { color: #333; }
                    .section { margin-bottom: 20px; }
                </style>
            </head>
            <body>
                <h1>Test Resume</h1>
                <div class="section">
                    <h2>John Doe</h2>
                    <p>Email: john@example.com | Phone: (123) 456-7890</p>
                </div>
                <div class="section">
                    <h3>Experience</h3>
                    <p>Software Developer at Test Company</p>
                    <p>Developed test applications and fixed bugs.</p>
                </div>
                <div class="section">
                    <h3>Skills</h3>
                    <ul>
                        <li>JavaScript</li>
                        <li>React</li>
                        <li>Node.js</li>
                    </ul>
                </div>
            </body>
            </html>
        `

        const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        })

        const page = await browser.newPage()
        await page.setContent(testResumeHtml, { waitUntil: 'networkidle0' })

        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
        })

        await browser.close()

        console.log("Test resume PDF generated successfully, size:", pdfBuffer.length)
        res.setHeader('Content-Type', 'application/pdf')
        res.setHeader('Content-Disposition', 'attachment; filename="test-resume.pdf"')
        res.send(pdfBuffer)
    } catch (error) {
        console.error("Error in test resume PDF generation:", error)
        res.status(500).json({ error: error.message })
    }
})

// Test route for HTML validation
app.get("/api/test-html-validation", async (req, res) => {
    try {
        const { generateFallbackResumeHtml } = require("./services/ai.service")
        const testHtml = generateFallbackResumeHtml({
            resume: "Test resume content",
            selfDescription: "Test self description",
            jobDescription: "Test job description"
        })

        console.log("Generated HTML length:", testHtml.length)
        console.log("HTML preview:", testHtml.substring(0, 200))

        res.set({
            "Content-Type": "text/html",
            "Content-Disposition": "inline"
        })
        res.send(testHtml)
    } catch (error) {
        console.error("HTML validation test failed:", error.message)
        res.status(500).json({ error: error.message })
    }
})

module.exports = app